name: movieapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  micro_core:
    path: packages/core/micro_core
  
  movie:
    path: packages/micro_apps/movie

  login:
    path: packages/micro_apps/login

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie.json
